

# -*- coding: utf-8 -*-
"""discretas

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1dC1cUWF3ZMERFzjS3Iwz4AGMrxqij3eP
"""

print("aX ≡ Y (mod:)")
x = int(input("x: "))
z = int(input("y: "))
y = int(input("mod: "))

i=1
while((x*i)%y!=z):
  i+=1
  
print("x ≡", i ,"(mod",y,")")

x = int(input("x:"))
y = int(input("y:"))
print("residuo ",x%y)
print("cosiente", x/y)
 
n=int(input("num 1: "))
m=int(input("num2 : "))
 
comunDivisor,iteracciones=mcd(n,m)
 
print("El comun divisor de {} y {} es {}".format(n,m,comunDivisor))
#print("Se ha encontrado en {} iteracciones".format(iteracciones))

import math
n = int(input("numero: "))
c=0
# for i in range(1,math.ceil(n/2)+1):
for i in range(1, n//2 + ((n % 2 != 0)*1)):
  if n % i == 0:
    c=c+1
print(c+1)

def factorizar(n):
    numeros_primos = iter(( 2, 3, 5, 7, 11, 13, 17, 19, 23, 29, 31, 37, 41, 43, 47, 53, 59, 61, 67, 71, 73, 79, 83, 89, 97))
    numero_primo_actual = next(numeros_primos)
    resultado = []
    cociente = None
    while cociente != 1:
        if n % numero_primo_actual != 0:
            numero_primo_actual = next(numeros_primos)
            continue
        resultado.append(numero_primo_actual)
        n = cociente = n / numero_primo_actual
    return resultado
n = int(input("Ingrese un número mayor a 1: "))
if n > 1:
    factores = factorizar(n)
    print(f"Factorización de {n} en primos:", " x ".join(map(str, factores)))
else:
    print("Ingrese un número mayor a 1.")